# Generated by Django 4.2.4 on 2025-01-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_apec', '0001_initial'),
        ('modulo_dot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actaNacimiento', models.CharField(max_length=255)),
                ('curp', models.CharField(max_length=18)),
                ('fechaNacimiento', models.DateField()),
                ('lugarNacimiento', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('nivelEducativo', models.CharField(max_length=50)),
                ('gradoRscolar', models.CharField(max_length=50)),
                ('certificadoEstudios', models.BooleanField()),
                ('nombrePadre', models.CharField(max_length=255)),
                ('ocupacionPadre', models.CharField(max_length=255)),
                ('telefonoPadre', models.CharField(max_length=15)),
                ('fotoVacunacion', models.ImageField(blank=True, null=True, upload_to='fotos_vacunacion/')),
                ('state', models.CharField(max_length=50)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id_Dependencias', models.AutoField(primary_key=True, serialize=False)),
                ('id_Dependiente', models.IntegerField()),
                ('id_Responsable', models.IntegerField()),
            ],
            options={
                'db_table': 'dependencias',
            },
        ),
        migrations.CreateModel(
            name='PromocionFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocionPDF', models.FileField(upload_to='promociones_pdfs/')),
            ],
            options={
                'db_table': 'promociones_fechas',
            },
        ),
        migrations.CreateModel(
            name='ReportesAcomp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.FileField(upload_to='reporte_acomp_pdfs/')),
                ('fecha', models.DateField()),
                ('figuraEducativa', models.CharField(max_length=120)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'reportes_acomp',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('categoria', models.CharField(choices=[('capacitación', 'Capacitación'), ('equipamiento', 'Equipamiento'), ('seguimiento', 'Seguimiento'), ('sin_asignar', 'Sin asignar')], default='sin_asignar', max_length=50)),
                ('reporte', models.FileField(upload_to='reporte_pdfs/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='RegistroMovilario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField()),
                ('condicion', models.CharField(max_length=120)),
                ('periodo', models.CharField(max_length=120)),
                ('Comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'registro_movilario',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo', models.CharField(max_length=100)),
                ('tipoRecibo', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'recibos',
            },
        ),
        migrations.CreateModel(
            name='PromocionesAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calfFinal', models.IntegerField(blank=True, null=True)),
                ('tipoPromocion', models.CharField(max_length=50)),
                ('Grado', models.CharField(max_length=50)),
                ('Nivel', models.CharField(max_length=50)),
                ('id_Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad')),
            ],
            options={
                'db_table': 'PromocionesAlumnos',
            },
        ),
        migrations.CreateModel(
            name='PagosFechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipoPago', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'pagos_fechas',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_Grupo', models.AutoField(primary_key=True, serialize=False)),
                ('Grado', models.DateField()),
                ('id_CCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad')),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dpe.alumno')),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
    ]
