# Generated by Django 4.2.4 on 2025-01-21 07:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_dot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanteAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacante_asignada', models.CharField(blank=True, max_length=255, null=True)),
                ('horas_cubiertas', models.IntegerField(blank=True, help_text='Horas totales cubiertas de la capacitación', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('Proceso', 'Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, null=True)),
                ('contexto', models.CharField(blank=True, max_length=100, null=True)),
                ('actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclo_asignado', models.DateField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('usuario_ec', models.ForeignKey(blank=True, limit_choices_to={'rol': 'EC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_ec', to='modulo_dot.usuario')),
                ('usuario_eca', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ECA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_eca', to='modulo_dot.usuario')),
                ('usuario_responsable', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ECAR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_asignadas', to='modulo_dot.usuario')),
            ],
            options={
                'verbose_name': 'Vacante Asignada',
                'verbose_name_plural': 'Vacantes Asignadas',
            },
        ),
    ]
