# Generated by Django 4.2.4 on 2025-01-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActCAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_capacitacion', models.IntegerField(blank=True, db_column='num_capacitacion', null=True)),
                ('nombre_region', models.CharField(default='Tabasco', max_length=200)),
                ('tema', models.CharField(blank=True, db_column='tema', max_length=200, null=True)),
                ('fecha_programada', models.CharField(blank=True, db_column='fecha_programada', max_length=45, null=True)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=45, null=True)),
                ('reporte', models.BinaryField(blank=True, db_column='reporte', null=True)),
            ],
            options={
                'db_table': 'ActCAP',
            },
        ),
        migrations.CreateModel(
            name='ActCAPMovil',
            fields=[
                ('id_ActCAP', models.AutoField(db_column='id_ActCAP', primary_key=True, serialize=False)),
                ('NumCapacitacion', models.IntegerField(db_column='NumCapacitacion')),
                ('TEMA', models.TextField(db_column='TEMA')),
                ('ClaveRegion', models.TextField(db_column='ClaveRegion')),
                ('NombreRegion', models.TextField(db_column='NombreRegion')),
                ('FechaProgramada', models.DateField(db_column='FechaProgramada')),
                ('Estado', models.TextField(db_column='Estado')),
                ('Reporte', models.TextField(db_column='Reporte')),
            ],
            options={
                'db_table': 'ActCap_Movil',
            },
        ),
        migrations.CreateModel(
            name='ActividadCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('fecha_inicio', models.DateTimeField(db_column='fecha_inicio')),
                ('fecha_fin', models.DateTimeField(db_column='fecha_fin')),
            ],
            options={
                'db_table': 'actividad_calendario',
            },
        ),
        migrations.CreateModel(
            name='AsignacionGrupo',
            fields=[
                ('id_AsignacionGrupo', models.AutoField(db_column='id_AsignacionGrupo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asignacion_grupo',
            },
        ),
        migrations.CreateModel(
            name='AsignacionMaestro',
            fields=[
                ('id_AsignacionMaestro', models.AutoField(db_column='id_AsignacionMaestro', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asignacion_maestro',
            },
        ),
        migrations.CreateModel(
            name='CapacitacionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_asignado', models.CharField(db_column='ciclo_asignado', max_length=20)),
                ('contexto', models.TextField(db_column='contexto')),
                ('actividad', models.TextField(db_column='actividad')),
                ('fecha', models.DateField(db_column='fecha')),
                ('horas_cubiertas', models.IntegerField(db_column='horas_cubiertas')),
                ('cat', models.CharField(db_column='cat', max_length=50)),
                ('finalizada', models.BooleanField(db_column='finalizada', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'capacitacion_inicial',
            },
        ),
        migrations.CreateModel(
            name='CapacitacionInicialMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_cubiertas', models.IntegerField(db_column='horas_cubiertas')),
            ],
            options={
                'db_table': 'capacitacion_inicial_movil',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_Materia', models.AutoField(db_column='id_Materia', primary_key=True, serialize=False)),
                ('grado', models.IntegerField(blank=True, db_column='grado', null=True)),
                ('nivel', models.CharField(blank=True, db_column='nivel', max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=45, null=True)),
            ],
            options={
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='ModuloCoordinadorStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(db_column='old_status', max_length=50)),
                ('new_status', models.CharField(db_column='new_status', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
            ],
            options={
                'db_table': 'modulo_coordinador_statushistory',
            },
        ),
        migrations.CreateModel(
            name='ReporteFiguraEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_reporte', models.FileField(db_column='archivo_reporte', upload_to='reportes_figura_educativa/')),
                ('fecha_reporte', models.DateField(db_column='fecha_reporte')),
                ('estado_reporte', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], db_column='estado_reporte', max_length=50)),
            ],
            options={
                'db_table': 'reporte_figura_educativa',
            },
        ),
        migrations.CreateModel(
            name='SolicitudEducadores',
            fields=[
                ('id_SolicitudEducadores', models.AutoField(db_column='id_SolicitudEducadores', primary_key=True, serialize=False)),
                ('nombreEscuela', models.CharField(blank=True, db_column='nombreEscuela', max_length=150, null=True)),
                ('tipoServicio', models.CharField(blank=True, db_column='tipoServicio', max_length=100, null=True)),
                ('periodo', models.CharField(blank=True, db_column='periodo', max_length=45, null=True)),
                ('numEducadores', models.IntegerField(blank=True, db_column='numEducadores', null=True)),
                ('justificacion', models.CharField(blank=True, db_column='justificacion', max_length=250, null=True)),
                ('contexto', models.CharField(blank=True, db_column='contexto', max_length=45, null=True)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=45, null=True)),
                ('educadoresAsignados', models.CharField(blank=True, db_column='educadoresAsignados', max_length=45, null=True)),
            ],
            options={
                'db_table': 'solicitud_educadores',
            },
        ),
    ]
