# Generated by Django 4.2.4 on 2025-01-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_dpe', '0001_initial'),
        ('home_empleado', '0001_initial'),
        ('modulo_apec', '0001_initial'),
        ('modulo_dot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudeducadores',
            name='id_CCT',
            field=models.ForeignKey(db_column='id_CCT', on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad'),
        ),
        migrations.AddField(
            model_name='solicitudeducadores',
            name='id_Usuario',
            field=models.ForeignKey(db_column='id_Usuario', on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='reportefiguraeducativa',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='modulocoordinadorstatushistory',
            name='aspirante_id',
            field=models.ForeignKey(db_column='aspirante_id', on_delete=django.db.models.deletion.CASCADE, related_name='aspirante_statushistory', to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='modulocoordinadorstatushistory',
            name='changed_by_id',
            field=models.ForeignKey(db_column='changed_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='changed_by_statushistory', to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='capacitacioninicialmovil',
            name='ec',
            field=models.ForeignKey(db_column='ec', on_delete=django.db.models.deletion.CASCADE, related_name='moviles', to='home_empleado.capacitacioninicial'),
        ),
        migrations.AddField(
            model_name='capacitacioninicialmovil',
            name='eca_id',
            field=models.ForeignKey(db_column='eca_id', on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='capacitacioninicial',
            name='ec_id',
            field=models.ForeignKey(db_column='ec_id', on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='capacitacioninicial',
            name='estado',
            field=models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.estado'),
        ),
        migrations.AddField(
            model_name='asignacionmaestro',
            name='id_Grupo',
            field=models.ForeignKey(db_column='id_Grupo', on_delete=django.db.models.deletion.CASCADE, to='modulo_dpe.grupo'),
        ),
        migrations.AddField(
            model_name='asignacionmaestro',
            name='id_Maestro',
            field=models.ForeignKey(db_column='id_Maestro', on_delete=django.db.models.deletion.CASCADE, to='modulo_dpe.alumno'),
        ),
        migrations.AddField(
            model_name='asignaciongrupo',
            name='id_Alumno',
            field=models.ForeignKey(db_column='id_Alumno', on_delete=django.db.models.deletion.CASCADE, to='modulo_dpe.alumno'),
        ),
        migrations.AddField(
            model_name='asignaciongrupo',
            name='id_Grupo',
            field=models.ForeignKey(db_column='id_Grupo', on_delete=django.db.models.deletion.CASCADE, to='modulo_dpe.grupo'),
        ),
        migrations.AddField(
            model_name='actcapmovil',
            name='id_Usuario',
            field=models.ForeignKey(db_column='id_Usuario', on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
        migrations.AddField(
            model_name='actcap',
            name='id_cct',
            field=models.ForeignKey(blank=True, db_column='id_cct', null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.comunidad'),
        ),
        migrations.AddField(
            model_name='actcap',
            name='id_microregion',
            field=models.ForeignKey(blank=True, db_column='id_microregion', null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.microrregion'),
        ),
        migrations.AddField(
            model_name='actcap',
            name='id_region',
            field=models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_apec.region'),
        ),
        migrations.AddField(
            model_name='actcap',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
