# Generated by Django 4.2.4 on 2024-12-01 02:31

from django.db import migrations, models
import form_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15, validators=[form_app.models.validate_phone_number])),
            ],
            options={
                'db_table': 'aspirante',
            },
        ),
    ]
