# Generated by Django 4.2.4 on 2025-01-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('status_seleccion', models.CharField(blank=True, choices=[('aceptado', 'aceptado'), ('pendiente', 'pendiente'), ('rechazado', 'rechazado')], default='pendiente', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Aspirante',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=100)),
                ('municipio_alcaldia', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante')),
            ],
            options={
                'db_table': 'Residencia',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_participacion', models.CharField(max_length=100)),
                ('ciclo_escolar', models.CharField(max_length=100)),
                ('programa_participacion', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('contexto', models.CharField(max_length=100)),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante')),
            ],
            options={
                'db_table': 'Participacion',
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habla_lengua_indigena', models.BooleanField()),
                ('lengua_indigena', models.CharField(blank=True, max_length=100, null=True)),
                ('talla_playera', models.CharField(max_length=10)),
                ('talla_pantalon', models.CharField(max_length=10)),
                ('talla_calzado', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('medio_publicitario', models.CharField(max_length=100)),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante')),
            ],
            options={
                'db_table': 'Informacion_Gestion',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=50, null=True)),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_app.aspirante')),
            ],
            options={
                'db_table': 'Informacion_Bancaria',
            },
        ),
    ]
