# Generated by Django 4.2.4 on 2024-12-01 19:26

from django.db import migrations, models
import django.db.models.deletion
import form_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico', models.CharField(max_length=150)),
                ('titulo_obtenido', models.CharField(max_length=255)),
                ('certificado_constancia', models.FileField(upload_to='documentos_academicos/', validators=[form_app.models.validate_file_size])),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones_academicas', to='form_app.aspirante')),
            ],
            options={
                'db_table': 'formacion_academica',
            },
        ),
    ]
