# Generated by Django 4.2.4 on 2024-12-01 19:39

import django.core.validators
from django.db import migrations, models
import form_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_formacionacademica'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacionacademica',
            name='habla_lengua_indigena',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='certificado_constancia',
            field=models.FileField(upload_to='documentos_academicos/', validators=[form_app.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='nivel_academico',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], default='Primaria', max_length=150),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='titulo_obtenido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
