# Generated by Django 4.2.4 on 2024-12-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_formacionacademica_habla_lengua_indigena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacionacademica',
            name='titulo_obtenido',
        ),
    ]
