# Generated by Django 4.2.4 on 2024-12-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0004_remove_formacionacademica_titulo_obtenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='rol',
            field=models.CharField(default='Aspirante', max_length=10),
        ),
    ]
