# Generated by Django 4.2.4 on 2024-12-01 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellidopa', models.CharField(max_length=150)),
                ('apellidoma', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_empleados/')),
                ('rol', models.CharField(choices=[('DOT', 'Director de Operaciones y Tecnología'), ('CT', 'Coordinador Territorial'), ('EC', 'Educador Comunitario'), ('ECA', 'Educador Comunitario de Acompañamiento Microrregional'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional'), ('APEC', 'Asesor de Promoción y Educación Comunitaria'), ('DEP', 'Desarrollo Educativo Profesional')], max_length=10)),
                ('contrasenia', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
