# Generated by Django 4.2.4 on 2025-01-21 07:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidopa', models.CharField(max_length=255)),
                ('apellidoma', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('formacion_academica', models.CharField(max_length=255)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotografias_personales/')),
            ],
            options={
                'db_table': 'datos_personales',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('contrasenia', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(choices=[('CT', 'Coordinador Territorial'), ('DECB', 'Dirección de Educación Comunitaria e Inclusión Social'), ('DPE', 'Dirección de Planeación y Evaluación'), ('EC', 'Educador Comunitario'), ('ECA', 'Educador Comunitario de Acompañamiento Microrregional'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional'), ('APEC', 'Asesor de Promoción y Educación Comunitaria'), ('DOT', 'Dirección de Operación Territorial'), ('ASPIRANTE', 'aspirante')], default='ASPIRANTE', max_length=10)),
                ('usuario_rol', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='DocumentosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_oficial', models.FileField(blank=True, null=True, upload_to='documentos_identificacion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('comprobante_domicilio', models.FileField(blank=True, null=True, upload_to='documentos_domicilio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('certificado_estudio', models.FileField(blank=True, null=True, upload_to='documentos_estudio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('datos_personales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='modulo_dot.datospersonales')),
            ],
            options={
                'verbose_name': 'Documento Personal',
                'verbose_name_plural': 'Documentos Personales',
                'db_table': 'documentos_personales',
            },
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario'),
        ),
    ]
