# Generated by Django 4.2.4 on 2025-01-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_dot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConveniosFiguras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_numero', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('convenio_pdf', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('firma_digital', models.FileField(blank=True, null=True, upload_to='firmas/')),
                ('estado_convenio', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=50)),
                ('tipo_convenio', models.CharField(choices=[('CUD', 'CUD'), ('Inicial', 'Inicial'), ('Otro', 'Rechazado')], default='Inicial', max_length=50)),
                ('firmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmado_por', to='modulo_dot.usuario')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_dot.usuario')),
            ],
            options={
                'db_table': 'convenio_digital',
            },
        ),
    ]
