

ESTADOS_MEXICO = [
    ('aguascalientes', 'Aguascalientes'),
    ('baja_california', 'Baja California'),
    ('baja_california_sur', 'Baja California Sur'),
    ('campeche', 'Campeche'),
    ('chiapas', 'Chiapas'),
    ('chihuahua', 'Chihuahua'),
    ('ciudad_de_mexico', 'Ciudad de México'),
    ('coahuila', 'Coahuila'),
    ('colima', 'Colima'),
    ('durango', 'Durango'),
    ('guanajuato', 'Guanajuato'),
    ('guerrero', 'Guerrero'),
    ('hidalgo', 'Hidalgo'),
    ('jalisco', 'Jalisco'),
    ('edo_mexico', 'Estado de México'),
    ('michoacan', 'Michoacán'),
    ('morelos', 'Morelos'),
    ('nayarit', 'Nayarit'),
    ('nuevo_leon', 'Nuevo León'),
    ('oaxaca', 'Oaxaca'),
    ('puebla', 'Puebla'),
    ('queretaro', 'Querétaro'),
    ('quintana_roo', 'Quintana Roo'),
    ('san_luis_potosi', 'San Luis Potosí'),
    ('sinaloa', 'Sinaloa'),
    ('sonora', 'Sonora'),
    ('tabasco', 'Tabasco'),
    ('tamaulipas', 'Tamaulipas'),
    ('tlaxcala', 'Tlaxcala'),
    ('veracruz', 'Veracruz'),
    ('yucatan', 'Yucatán'),
    ('zacatecas', 'Zacatecas'),
]

# Lista de bancos en México (puedes agregar más según sea necesario)
BANCO_CHOICES = [
    ('BBVA', 'BBVA'),
    ('Santander', 'Santander'),
    ('Banorte', 'Banorte'),
    ('HSBC', 'HSBC'),
    ('Citibanamex', 'Citibanamex'),
    ('Scotiabank', 'Scotiabank'),
    ('Inbursa', 'Inbursa'),
    ('Bajío', 'Bajío'),
    ('Monex', 'Monex'),
    ('BancoAzteca', 'Banco Azteca'),
    ('Banregio', 'Banregio'),
    ('Compartamos', 'Compartamos'),
    ('Otros', 'Otros'),  # Opción adicional en caso de que el banco no esté en la lista
]

LINGUA_CHOICES = [
    ('Akateko', 'Akateko'),
    ('Amuzgo', 'Amuzgo'),
    ('Awakateko', 'Awakateko'),
    ('Ayapaneco', 'Ayapaneco'),
    ('Cora', 'Cora'),
    ('Cucapá', 'Cucapá'),
    ('Cuicateco', 'Cuicateco'),
    ('Chatino', 'Chatino'),
    ('Chichimeco Jonaz', 'Chichimeco Jonaz'),
    ('Chinanteco', 'Chinanteco'),
    ('Chocholteco', 'Chocholteco'),
    ('Chontal de Oaxaca', 'Chontal de Oaxaca'),
    ('Chontal de Tabasco', 'Chontal de Tabasco'),
    ('Chuj', 'Chuj'),
    ('Guarijío', 'Guarijío'),
    ('Huasteco', 'Huasteco'),
    ('Huave', 'Huave'),
    ('Huichol', 'Huichol'),
    ('Ixcateco', 'Ixcateco'),
    ('Ixil', 'Ixil'),
    ('Jakalteko', 'Jakalteko'),
    ('Kaqchikel', 'Kaqchikel'),
    ('Kickapoo', 'Kickapoo'),
    ('Kiliwa', 'Kiliwa'),
    ('Kumiai', 'Kumiai'),
    ('Lacandón', 'Lacandón'),
    ('Mam', 'Mam'),
    ('Matlatzinca', 'Matlatzinca'),
    ('Maya', 'Maya'),
    ('Mayo', 'Mayo'),
    ('Mazahua', 'Mazahua'),
    ('Mazateco', 'Mazateco'),
    ('Mixe', 'Mixe'),
    ('Mixteco', 'Mixteco'),
    ('Náhuatl', 'Náhuatl'),
    ('Oluteco', 'Oluteco'),
    ('Otomí', 'Otomí'),
    ('Paipai', 'Paipai'),
    ('Pame', 'Pame'),
    ('Pápago', 'Pápago'),
    ('Pima', 'Pima'),
    ('Popoloca', 'Popoloca'),
    ('Popoluca de la Sierra', 'Popoluca de la Sierra'),
    ('Sayulteco', 'Sayulteco'),
    ('Seri', 'Seri'),
    ('Tarahumara', 'Tarahumara'),
    ('Tarasco', 'Tarasco'),
    ('Teko', 'Teko'),
    ('Tepehua', 'Tepehua'),
    ('Tepehuano del norte', 'Tepehuano del norte'),
    ('Tepehuano del sur', 'Tepehuano del sur'),
    ('Texistepequeño', 'Texistepequeño'),
    ('Tlahuica', 'Tlahuica'),
    ('Tlapaneco', 'Tlapaneco'),
    ('Tojolabal', 'Tojolabal'),
    ('Totonaco', 'Totonaco'),
    ('Triqui', 'Triqui'),
    ('Tseltal', 'Tseltal'),
    ('Tsotsil', 'Tsotsil'),
    ('Yaqui', 'Yaqui'),
    ('Zapoteco', 'Zapoteco'),
    ('Zoque', 'Zoque')
]

formacion_academica_CHOICES = [
    ("preparatoria", "Preparatoria"),
    ("tecnica", "Técnica"),
    ("universidad", "Universidad"),
]

