# Generated by Django 4.2.4 on 2025-01-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('CT', 'Coordinador Territorial'), ('DECB', 'Dirección de Educación Comunitaria e Inclusión Social'), ('DPE', 'Dirección de Planeación y Evaluación'), ('EC', 'Educador Comunitario'), ('ECA', 'Educador Comunitario de Acompañamiento Microrregional'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional'), ('APEC', 'Asesor de Promoción y Educación Comunitaria'), ('DOT', 'Dirección de Operación Territorial'), ('ASPIRANTE', 'aspirante')], default='ASPIRANTE', max_length=10)),
            ],
            options={
                'db_table': 'Usuario_rol',
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('baja', 'Baja'), ('reincorporacion', 'Reincorporación'), ('reingreso', 'Reingreso'), ('suspendida', 'Suspendida'), ('capacitacion', 'Capacitacion')], default='suspendida', max_length=15)),
            ],
            options={
                'db_table': 'Statuses',
            },
        ),
    ]
