# Generated by Django 4.2.4 on 2024-11-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuariorol',
            table='Usuario_rol',
        ),
    ]
