# Generated by Django 4.2.4 on 2024-11-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_usuariorol_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
