# Generated by Django 4.2.4 on 2025-01-21 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('inicio_ciclo', 'Inicio de Ciclo Escolar'), ('termino_ciclo', 'Término de Ciclo Escolar'), ('colegiado_regional', 'Colegiado Regional'), ('colegiado_microrregional', 'Colegiado Microrregional'), ('promocion_captacion', 'Promoción y Captación'), ('capacitacion', 'Capacitación')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'calendar_event',
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_date_pay', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('movilidad', 'Movilidad'), ('hospedaje', 'Hospedaje y alimentos para la formación'), ('continuidad', 'Continuidad de estudios'), ('conectividad', 'Conectividad móvil'), ('vestuario', 'Vestuario de identidad'), ('atencion_medica', 'Atención médica'), ('fin_de_año', 'Apoyo económico de fin de año'), ('fallecimiento', 'Apoyo a beneficiarios por fallecimiento'), ('EC_INIT', 'Educador Comunitario de Inicial'), ('EC', 'Educador Comunitario de Preescolar, Primaria y Secundaria'), ('ECA', 'Educador Comunitario de Acompañamiento'), ('ECAR', 'Educador Comunitario de Acompañamiento Regional')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('rechazado', 'Rechazado'), ('completado', 'Completado'), ('completado-inicial', 'Completado-Inicial')], default='pendiente', max_length=20)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_schedule',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='payment_evidence/')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_payments', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_status', to='modulo_DECB.paymentschedule')),
            ],
            options={
                'verbose_name': 'Estado de Pago',
                'verbose_name_plural': 'Estados de Pagos',
                'db_table': 'payment_status',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='modulo_DECB.paymentschedule')),
            ],
            options={
                'db_table': 'payment_history',
            },
        ),
    ]
